name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - '1.66' # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Test
        run: |
          cargo test --package=confik-macros
          cargo test --package=confik --no-default-features
          cargo test --package=confik --no-default-features --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Clippy
        run: |
          cargo clippy --workspace --no-default-features
          cargo clippy --workspace --no-default-features --all-features
          cargo hack --feature-powerset --depth=3 clippy --workspace

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt -- --check
